### ISSUE TITLE
add coerce parameter to convert date to datetime and viceversa

### ISSUE THREAD

**Issue by Lorenzo-ITA** [Cottonwood-Technology/ValidX#13]
Im trying to perform a validation like this:
`validation = OneOf(Date(), Datetime())` but the implicit conversion breaks my logic.

Example: 
```
def validate_end(end: Union[date, datetime]):
    validation = OneOf(Date(), Datetime())                   # Date() first
    return validation(end) 
```
validate_end(**datetime**(2022, 10, 10, **10, 11**)) ---> **date**(2022, 10, 10)
validate_end(date(2022, 10, 10)) ----------------> date(2022, 10, 10) 
```
def validate_end(end: Union[date, datetime]):
    validation = OneOf(Datetime(), Date())                   # Datetime() first
    return validation(end) 
```
validate_end(datetime(2022, 10, 10, 10, 11)) ---> datetime(2022, 10, 10, 10, 11)
validate_end(**date**(2022, 10, 10)) ----------------> **datetime**(2022, 10, 10, 0, 0)

It's possible to add a coerce parameter to avoid this unwanted behavior?

**Comment by kr41** [comment]
Most likely, I will not "fix" it. However, could you explain, why do you need it? 

As a workaround, you can use ``OneOf(Type(date), Type(datetime))``

**Comment by Lorenzo-ITA** [comment]
the next function accepts only datetime and if the user passes me a date I have to combine it with time.max

**Comment by kr41** [comment]
But why `time.max`? If I pass into a function value `2023-02-20`, I expect it will be processed like `2023-02-20 00:00:00`, not like `2023-02-20 23:59:59`.

**Comment by Lorenzo-ITA** [comment]
Today date is date(2023, 2, 20)

If the user want to see data:
- from **date** date(2023, 1, 1)
- to **date**  date(2023, 2, 20)
it means that today's data must be included, so date(2023, 2, 20) must be converted to datetime(2023, 2, 20, 23, 59, 59, 999999)

If the user want to see data:
- from **datetime** datetime(2023, 1, 1)
- to **datetime**  datetime(2023, 2, 20)
it means that the data must be excluded after the datetime that the user have set as **end**, so today's data must not be included

**Comment by kr41** [comment]
That makes sense to me. So I see the following solution:
```python
start_date = Datetime()  # converts date to YYYY-MM-DD 00:00:00
end_date = Datetime(some_param=True)  # converts date to YYYY-MM-DD 23:59:59
```
The only problem is to come up with a good name for `some_param`.

**Comment by Lorenzo-ITA** [comment]
A good name could be "combine_max_time" or "combine_time_max" (default = False)
```
combine_time_max: bool = False
```

If you want to do it more generic, the param can be a datetime.time type: the name can be "time_to_combine"
```
time_to_combine: time = time.min
```
I imagine that someone in the future may need this for example to set the time at noon (12:00:00) perhaps for graphic reasons

**Comment by kr41** [comment]
You're right, more generic solution is better. I think, `default_time: time = time.min` is the best name for the param.

**Comment by kr41** [comment]
I opened #15 ticket for the solution we came with. This ticket I will close, because it has misleading title.
