### ISSUE TITLE
Cloning Const(False) fails

### ISSUE THREAD

**Issue by draggeta** [Cottonwood-Technology/ValidX#19]
When cloning a Const(False):
```python
import validx.py

a = validx.py.Const(False)
a.clone()
```
I get an error:
```python
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "c:\git\parsing\.venv\lib\site-packages\validx\py\abstract.py", line 226, in clone
    return self.load(self.dump(), update, unset, **kw)
  File "c:\git\parsing\.venv\lib\site-packages\validx\py\abstract.py", line 196, in load
    return _load_recurcive(params, _update, _unset)
  File "c:\git\parsing\.venv\lib\site-packages\validx\py\abstract.py", line 252, in _load_recurcive
    return class_(**result)
TypeError: Const.__init__() missing 1 required positional argument: 'value'
```

This error is caused by the `params` method in the `Validator` class in `abstract.py`:
```python
    def params(self):
        for slot in self.__slots__:
            value = getattr(self, slot)
            if value is not None and value is not False:
                yield slot, value
```
I don't know what the procedure is for a pull request (or if you'd rather do it yourself), but checking if the class isn't an instance of `Const` and then allowing `False` as a value would probably fix it.

**Comment by kr41** [comment]
>  checking if the class isn't an instance of Const and then allowing False as a value would probably fix it.

I'll try to find more elegant solution. However the bug itself is really cool :)

**Comment by draggeta** [comment]
That makes sense as this is a parent class. Thank you for the quick reply btw.
