### ISSUE TITLE
Support Enum class in options

### ISSUE THREAD

**Issue by artsmolin** [Cottonwood-Technology/ValidX#2]
It would be really cool if the "options" argument supported Enum, not just lists.

**Comment by kr41** [comment]
It might be not obvious from the docs, however there is already solution for enums. Just use [Type](https://validx.readthedocs.io/en/latest/reference.html#validx.py.Type) validator: `enum_validator = Type(MyEnum, coerce=True)`

**Comment by kr41** [comment]
BTW, enum classes are now supported as options in version 0.6. However, enum class should explicitly inherit from generic class (`int` for `Int` validators, `str` for `Str` validators, etc.):

```pycon
>>> from validx import Int
>>> from enum import Enum
>>> class Options(int, Enum):
...   one = 1
...   two = 2
... 
>>> v = Int(options=Options)
>>> v(1)
1
>>> v(2)
2
>>> v(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "validx/cy/numbers.pyx", line 127, in validx.cy.numbers.Int.__call__
validx.exc.errors.OptionsError: <OptionsError(expected=frozenset({<Options.one: 1>, <Options.two: 2>}), actual=3)>
```
