### ISSUE TITLE
list vs frozenset about the options parameter of Str

### ISSUE THREAD

**Issue by mathbeal** [Cottonwood-Technology/ValidX#4]
Hi,

there is a loss of information during the recent version update:

`Str(options=['a','b','c'])`

to

`Str(options=frozenset({'a','b','c'})) `

because frozenset are immutable, unique and **unordered**

The uniqueness make sense, but it's most likely a frozen **ordered** set than an frozen set.

The ordered property is useful in somes cases, in tests for instance:

I would like to check if a list of string is sorted according to the schema definition.

with `List(Str(options=['a', 'b', 'c']))`

validx tells me that the following lists are correct:

- `['a', 'b', 'c']`
- `['a', 'b', 'c', 'b']`
- `['c', 'a']`
- `['c']`

but what if you need to check too that index('a') < index('b') < index('c') too ?

(I was reusing the str.options attribute to compare indexes, but with frozenset the ordered property is lost).

```
schema = Str(options=['a', 'b', 'c'])
<Str(options=frozenset({'b', 'c', 'a'}))>
```

Is there another way to do it with validx ?

**Comment by kr41** [comment]
I am not sure I understood the task you are trying to solve. But whether just sorting a result is not enough?
```python
value = list_validator(value)
value.sort()
```

BTW, I'm going to add the feature into `List` validator, so it could be constructed like this:
```python
sorted_strings = List(Str(...), ordered='asc')
sorted_dicts = List(Dict(...), ordered='desc', order_key=lambda item: ...)
```

**Comment by mathbeal** [comment]
Yes, I would like to check if a list of Str with options is sorted according to options.

```
schema = List(Str(options=['a', 'c', 'b'])) # deliberately not sorted according to asc or desc.
schema(['a', 'c'])  # ok
schema(['a', 'a', 'c']) # ok
schema(['a', 'b']) # ok
schema(['a', 'b', 'c']) # nok, not sorted according to options.
```

**Comment by kr41** [comment]
It looks weird for me. Could you give me a real life problem that you are trying to solve?

**Comment by mathbeal** [comment]
Yes, you're right, it's maybe too specific for my case (the need is to validate a list with ordered optional values, but not sorted according to asc/desc).

In my situation, there are several kinds of documents  that must be returned in a specific order, all of them are optional. I need to check :
- that a document is allowed to be returned,
- that all documents are sorted according to the specific order.

I thought about it : it's not really common in real life.

**Comment by kr41** [comment]
Here is a workaround:

```python
options = {option: index for index, option in enumerate(['a', 'c', 'b'])}
sort_key = lambda option: options[option]
schema = List(Str(options=options.keys()))

...

value = schema(['a', 'b', 'c'])
value.sort(key=sort_key)
assert value == ['a', 'c', 'b']
```
