### ISSUE TITLE
Unable to distinguish between bool and int

### ISSUE THREAD

**Issue by DeusFacticius** [Cottonwood-Technology/ValidX#8]
I realize this is grounded in python's unique quirk of `bool` being derived from `int`, and thus the values `True` and `False` are both valid `int` values (1 and 0, respectively), but for the use case of validating blobs of data parsed from JSON (where boolean values are distinct from numbers), I cannot seem to find a way to enforce that a value must strictly be a number (either `float` or `int`) and _not_ a boolean value.

I believe adding an option to `validx.Type()` to invert the result of the type check would be sufficient for this use case, such that by composing with `AllOf`, it'd be possible to prevent `True` and `False` from being valid, e.g.:
```python
StrictInteger = validx.AllOf(
  validx.Int(),
  validx.Type(tp=bool, invert=True)
)
```

The specific case I'm trying to solve is actually in the context of timestamps represented by numeric UNIX epochs, where the behavior is much more surprising (especially when the data is coming from JSON), e.g.:
```python
import validx
from datetime import (datetime, timezone)

# Timestamp validator (which also conveniently coerces into a datetime object)
UnixTimestamp = validx.Datetime(unixts=True, tz=timezone.utc)

assert UnixTimestamp(False) == datetime.fromtimestamp(0, tz=timezone.utc) # e.g. datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
assert UnixTimestamp(True) == datetime.fromtimestamp(1, tz=timezone.utc) # e.g. datetime.datetime(1970, 1, 1, 0, 0, 1, tzinfo=datetime.timezone.utc)
```

Is there any other workaround that I'm not seeing?

**Comment by kr41** [comment]
Hi, it's definitely a bug. Validators should not accept `bool` values as `int` ones by default. You can use the following workaround until I fix it.

```python
from abc import ABC
from datetime import datetime, timezone

import validx


class StrictNumber(ABC):
    @classmethod
    def __subclasshook__(cls, subclass):
        return issubclass(subclass, (int, float)) and subclass is not bool


timestamp = validx.AllOf(
    validx.Type(StrictNumber),
    validx.Datetime(unixts=True, tz=timezone.utc),
)

assert timestamp(0) == datetime.fromtimestamp(0, timezone.utc)
assert timestamp(0.1) == datetime.fromtimestamp(0.1, timezone.utc)
timestamp(False)  # should raise validation error
```

Here is the output

```
$ python3 strict_number.py 
Traceback (most recent call last):
  File "strict_number.py", line 20, in <module>
    timestamp(False)  # should raise validation error
  File "validx/cy/pipelines.pyx", line 41, in validx.cy.pipelines.AllOf.__call__
  File "validx/cy/pipelines.pyx", line 39, in validx.cy.pipelines.AllOf.__call__
  File "validx/cy/special.pyx", line 203, in validx.cy.special.Type.__call__
validx.exc.errors.InvalidTypeError: <#0: InvalidTypeError(expected=<class '__main__.StrictNumber'>, actual=<class 'bool'>)>
```
